name: Release apex version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v4
      - name: Bump version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          npm version ${VERSION} --no-git-tag-version
          (cd server && npm version ${VERSION} --no-git-tag-version)
          (cd client && npm version ${VERSION} --no-git-tag-version)
      - name: Commit and tag release
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.version }} release
          tagging_message: ${{ inputs.version }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ inputs.version }}
